import Head from "next/head";
import React, { useEffect } from "react";
import About from "../../components/About/About";
import WebLayout from "../../components/Layout/WebLayout";
import PageHeader from "../../components/PageHeader/PageHeader";
import { useSelector, useDispatch } from "react-redux";
import { toggleNavClose } from "../../redux/website/Navigation/NavigationSlice";

const index = () => {
  const navToggleState = useSelector((state) => state.navigation.isToggle);
  const dispatch = useDispatch();
  useEffect(() => {
    console.log(navToggleState);
    if (navToggleState) {
      dispatch(toggleNavClose());
    }
  }, []);
  return (
    <>
      <Head>
        <title>About FitGoo!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WebLayout>
          <PageHeader
            title="About FitGoo"
            description="Generated by create next app"
          />
          <About />
        </WebLayout>
      </main>
    </>
  );
};

export default index;
